### ISSUE TITLE
Grid issue

### ISSUE THREAD

**Issue by shaktigoap** [hackinout/InOut4-landing#2]
@akashnimare Check out the attached image for grid correction.
<img width="593" alt="screen shot 2017-03-06 at 9 35 54 pm" src="https://cloud.githubusercontent.com/assets/1829208/23618151/6aa19752-02b5-11e7-9a79-5f3dfd55f665.png">

<img width="577" alt="screen shot 2017-03-06 at 9 36 03 pm" src="https://cloud.githubusercontent.com/assets/1829208/23618149/6a9b34d4-02b5-11e7-8a0c-b9abe9e1d6f8.png">

<img width="545" alt="screen shot 2017-03-06 at 9 36 11 pm" src="https://cloud.githubusercontent.com/assets/1829208/23618150/6aa10f6c-02b5-11e7-97fd-9bcb5367ca94.png">

**Comment by akashnimare** [comment]
Fixed although 5-10 px margin is still there.
