### ISSUE TITLE
Embedded youtube video to cover the full page

### ISSUE THREAD

**Issue by shaktigoap** [hackinout/InOut4-landing#4]
Right now clicking the image starts the video in the defined div/container which doesn't look good UX wise as well. I think that covering up the page would look better. @vikas-parashar @dalpat might add more to it!

<img width="1213" alt="screen shot 2017-03-06 at 9 53 20 pm" src="https://cloud.githubusercontent.com/assets/1829208/23618754/5b6ca2f2-02b7-11e7-9226-89a6e17072ec.png">

**Comment by vikas-parashar** [comment]
That depends on the importance of video. If video is the primary content and we want user's full attention, we should open it in a modal window with overlay. Otherwise keeping it size limited to div size good idea so user can browse around without being forced to watch it.

**Comment by shaktigoap** [comment]
Our primary intention of embedding the video is to allow hackers/potential sponsors understand more about past editions of InOut. Don't you think?

**Comment by vikas-parashar** [comment]
The site has 3 type of content: Subscription form, video and the past sponsors. By primary content I mean the one user must focus on. If we want him to be able to subscribe or to browse the sponsors without breaking the flow, video shouldn't be played in full screen/modal. If we want user to focus on video first, then we should play it in modal or full screen. IMO video should be the primary content.

**Comment by akashnimare** [comment]
Fixed.
