### ISSUE TITLE
Bad UI  response on newsletter subscription 

### ISSUE THREAD

**Issue by Prakharsvnit** [hackinout/InOut4-landing#9]
@akashnimare Clicking on subscribe button after entering email id returns bad UI.
 
![screenshot from 2017-04-12 18-52-42](https://cloud.githubusercontent.com/assets/19989448/24961624/0c5690a2-1fb7-11e7-876c-ee9f7fd95d76.png)

**Comment by shaktigoap** [comment]
@Prakharsvnit All CSS files are not loaded it seems. Did you try reloading it?

**Comment by Prakharsvnit** [comment]
@shaktigoap After reloading the page works fine. but clicking on subscribe button right shifts the about container.
